plugins:
  suspend_resume_plugin:
    executor: central_deployment_agent
    package_name: cloudify-suspend-resume-plugin
    package_version: '1.0'

node_types:

  cloudify.nodes.AttributePoller:
    derived_from: cloudify.nodes.Root
    properties:
      description:
        type: string
        default: 'Manual condition status'
      runtime_property:
        type: string
        default: 'STATUS'
      retry_interval:
        type: integer
        default: 5
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: suspend_resume_plugin.suspend_resume_plugin.tasks.suspend
          max_retries: -1
          inputs:
            retry_interval:
              default: { get_property: [ SELF, retry_interval ] }
        delete:
          implementation: suspend_resume_plugin.suspend_resume_plugin.tasks.clear
      cloudify.interfaces.suspend_resume:
        resume:
          implementation: suspend_resume_plugin.suspend_resume_plugin.tasks.resume
        fail:
          implementation: suspend_resume_plugin.suspend_resume_plugin.tasks.fail
