plugins:
  suspend_resume_plugin:
    executor: central_deployment_agent
    package_name: cloudify-suspend-resume-plugin
    package_version: '1.0'

node_types:

  cloudify.nodes.AttributePoller:
    derived_from: cloudify.nodes.Root
    properties:
      description:
        default: 'Manual condition status'
      runtime_property:
        default: 'STATUS'
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: suspend_resume_plugin.suspend_resume_plugin.tasks.suspend
          inputs:
            retry_interval:
              default: 5
        delete:
          implementation: suspend_resume_plugin.suspend_resume_plugin.tasks.clear
      cloudify.interfaces.suspend_resume:
        resume:
          implementation: suspend_resume_plugin.suspend_resume_plugin.tasks.resume
        fail:
          implementation: suspend_resume_plugin.suspend_resume_plugin.tasks.fail
